export {
  buildCartItemPayload,
  collectCustomizationPolicies,
  colorNameToHex,
  getCartLineOptions,
  getColorSurcharge,
  getInitialWritingColor,
  isNoSurchargeColor,
  isWristbandProduct,
  matchesCartLine,
  resolveDisplayImage,
  resolveProductImageStyle,
  resolveProductUnitPrice,
  validateWristbandSelection,
  toDefaultCartPayload,
  type CustomizableCartItem,
  type CustomizableLine,
  type PricedProduct,
} from '@/services/productCustomizationService';
